### ISSUE TITLE
program error

### ISSUE THREAD

**Issue by science110** [SafeRoboticsLab/iLQR_jax_racing#1]
ImportError: cannot import name 'libspline' from partially initialized module 'pyspline' (most likely due to a circular import) (D:\pythonProject-ilqr\venv\lib\site-packages\pyspline\__init__.py)

**Comment by HaiminClack** [comment]
Please carefully review and follow the build instructions of pySpline here: [https://mdolab-pyspline.readthedocs-hosted.com/en/latest/building.html](https://mdolab-pyspline.readthedocs-hosted.com/en/latest/building.html)
